diagnostico/urls.py
from django.conf import settings
from .views import *


from django.conf.urls import url
from factura.views import apiFactura
from . import views

app_name = 'diagnostico'

urlpatterns = [
    url(r'^$', listarDiagnosticos, name='ListarDiagnosticos'),
    url(r'^crear$', crearDiagnostico, name='CrearDiagnostico'),
    url(r'^(?P<diagnostico_id>[0-9]+)/$', views.detalleDiagnostico, name='detail'),
    url(r'^editar/(?P<id>\d+)$', editarDiagnostico, name='EditarDiagnostico'),
    url(r'^eliminar/(?P<id>\d+)$', eliminarDiagnostico, name='EliminarDiagnostico'),
    url(r'^guardar$', guardarDiagnostico, name='GuardarDiagnostico'),
    url(r'^reportes/$', views.reportes, name='reportes'),
    url(r'^reporte/(?P<paciente_cedula>[0-9]+)/$', views.reporteTotal),
    url(r'^reporte/$', views.reporte),
    #url(r'^api/$', views.apiDiagnostico, name="ApiDiagnostico"),
]

kala/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import login, logout, password_change, password_change_done, password_reset, \
                                        password_reset_done, password_reset_complete, password_reset_confirm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm

urlpatterns = [
    url(r'^', include('kalaapp.urls')),
    url(r'^api/', include('clienteRest.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^paciente/', include('paciente.urls')),
    url(r'^personal/', include('personal.urls')),
    url(r'^factura/', include('factura.urls')),
    url(r'^fisioterapia/', include('fisioterapia.urls')),
    url(r'^nutricion/', include('nutricion.urls')),
    url(r'^diagnostico/', include('diagnostico.urls')),

    url(r'^login/$', login, 
        {'template_name': 'login.html', 'authentication_form': AuthenticationForm, 'redirect_authenticated_user': True}, 
        name='login'),
    url(r'^logout/$', logout, 
        {'next_page': settings.LOGIN_URL}, 
        name="logout"),
    url(r'^password_change/$', password_change,
        {'template_name': 'password_change.html', 'password_change_form': PasswordChangeForm}, 
        name='password_change'),
    url(r'^password_change/done/$', password_change_done, 
        {'template_name': 'password_change_done.html'},
        name='password_change_done'),
    url(r'^password_reset/$', password_reset,
        {'template_name': 'password_reset.html',
         'password_reset_form': PasswordResetForm},
        name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done,
        {'template_name': 'password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, 
        {'template_name': 'password_reset_confirm.html', 'set_password_form': SetPasswordForm},
        name='password_reset_confirm'),
    url(r'reset/done/$', password_reset_complete, 
        {'template_name': 'password_reset_complete.html'},
        name='password_reset_complete'),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

diagnostico/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from kalaapp.models import TimeModel, Usuario
from personal.models import Personal
from paciente.models import Paciente
# Create your models here.


class DiagnosticoFisioterapia(TimeModel):
    personal = models.ForeignKey(Personal, on_delete=models.DO_NOTHING)
    paciente = models.ForeignKey(Paciente, on_delete=models.DO_NOTHING)
    condiciones_previas = models.CharField(max_length=1000, default='', null=False)
    area_afectada = models.CharField(max_length=1000, default='', null=False)
    receta = models.CharField(max_length=1000, default='', null=False)
    rutina = models.OneToOneField('Rutina', on_delete=models.CASCADE, unique=True)
    estado = models.CharField(max_length=1, default='A')

    class Meta:
        db_table = 'diagnostico_fis'

    def __unicode__(self):
        return str(self.id)


class DiagnosticoNutricion(TimeModel):
    personal = models.ForeignKey(Personal, on_delete=models.DO_NOTHING)
    paciente = models.ForeignKey(Paciente, on_delete=models.DO_NOTHING)
    condiciones_previas = models.CharField(max_length=1000, default='', null=False)
    dieta = models.OneToOneField('Dieta', on_delete=models.CASCADE, unique=True)
    estado = models.CharField(max_length=1, default='A')

    class Meta:
        db_table = 'diagnostico_nut'


class Rutina(TimeModel):
    subrutina = models.ManyToManyField('Subrutina')
    estado = models.CharField(max_length=1, default='A')

    class Meta:
        db_table = 'rutina'


class Subrutina(TimeModel):
    nombre = models.CharField(max_length=1000, default='', null=False)
    detalle = models.CharField(max_length=1000, default='', null=False)
    veces = models.PositiveSmallIntegerField(default=0, null=False)           #50 veces
    repeticiones = models.PositiveSmallIntegerField(default=0, null=False)    #por 3 repeticiones
    descanso = models.PositiveSmallIntegerField(default=0, null=False)        #3 minutos entre cada repeticion
    link = models.URLField(max_length=500, default='', null=False)
    estado = models.CharField(max_length=1, default='A')

    class Meta:
        #managed = False
        db_table = 'subrutina'


class Dieta(TimeModel):
    descripcion = models.CharField(max_length=1000, default='', null=False)
    estado = models.CharField(max_length=1, default='A')

    class Meta:
        db_table = 'dieta'

DIAS = ((1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'),
        (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'))


class PlanNutDiario(TimeModel):
    dieta = models.ForeignKey('Dieta', on_delete=models.CASCADE, default='')
    dia = models.CharField(max_length=30, choices=DIAS, default='Lunes', null=False)
    desayuno = models.CharField(max_length=1000, default='', null=False)
    colacion1 = models.CharField(max_length=1000, default='', null=False)
    almuerzo = models.CharField(max_length=1000, default='', null=False)
    colacion2 = models.CharField(max_length=1000, default='', null=False)
    cena = models.CharField(max_length=1000, default='', null=False)
    estado = models.CharField(max_length=1, default='A')

    class Meta:
        db_table = 'plan_nut_diario'

diagnostico/views.py
'''
MODULO DIAGNOSTICO FISIOTERAPISTA Y NUTRICIONISTA

VERSION 2.0.0

ACTUALIZADO EN 15/07/2017

'''

# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
from django.contrib import messages
from django.db import transaction
from django.http import HttpResponseForbidden
from django.http import JsonResponse, HttpResponseServerError, HttpResponseNotFound
from django.db.models import Value
from django.db.models.functions import Concat
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from diagnostico.models import DiagnosticoFisioterapia, DiagnosticoNutricion, Dieta, PlanNutDiario
from kalaapp.views import paginar
from paciente.models import Paciente
from personal.models import Personal
from .models import Rutina, Subrutina, DIAS
from kalaapp.decorators import rol_required

# Create your views here.


'''
Funcion: listarDiagnosticos
Entradas: request
Salidas: - HttpResponse con template diagnostico_listar.ntml y la lista de todos los diagnosticos

Funcion que permite listar los diagnosticos existentes
'''


@login_required
@rol_required(roles=['fisioterapista', 'nutricionista'])
def listarDiagnosticos(request):
    template = 'diagnostico_listar.html'
    contexto = {}
    diagnosticos = None
    rol = None

    sesion = request.session.get('user_sesion', None)

    if sesion:
        rol = sesion.get('rol__tipo', None)

        if rol == 'fisioterapista':
            diagnosticos = DiagnosticoFisioterapia.objects.filter(estado='A', paciente__usuario__estado='A',
                                                                  personal_id=sesion.get('personal__id', 0))\
                .annotate(paciente_nombre_completo=Concat('paciente__usuario__nombre',
                                                          Value(' '), 'paciente__usuario__apellido')) \
                .annotate(paciente_id=Concat('paciente_id', Value('')))\
                .annotate(paciente_foto=Concat('paciente__usuario__foto', Value('')))\
                .annotate(cedula=Concat('paciente__usuario__cedula', Value('')))\
                .order_by('-creado')

        elif rol == 'nutricionista':
            diagnosticos = DiagnosticoNutricion.objects.filter(estado='A', paciente__usuario__estado='A',
                                                               personal_id=sesion.get('personal__id', 0))\
                .annotate(paciente_nombre_completo=Concat('paciente__usuario__nombre',
                                                          Value(' '), 'paciente__usuario__apellido')) \
                .annotate(paciente_id=Concat('paciente_id', Value('')))\
                .annotate(paciente_foto=Concat('paciente__usuario__foto', Value(''))) \
                .annotate(cedula=Concat('paciente__usuario__cedula', Value(''))) \
                .order_by('-creado') \

    contexto['diagnosticos'] = diagnosticos
    contexto['user_sesion'] = sesion

    return render(request, template_name=template, context=contexto)


'''
Funcion: crearDiagnostico
Entradas: request
Salidas: - HttpResponse con template crear.ntml y la lista de todas los pacientes

Funcion que permite crear un nuevo diagnostico
'''


@login_required
@rol_required(roles=['fisioterapista', 'nutricionista'])
@transaction.atomic
def crearDiagnostico(request):
    template = None
    contexto = {}
    pacientes = None
    rol = None

    sesion = request.session.get('user_sesion', None)

    if sesion:
        rol = sesion.get('rol__tipo', '')

    if request.method == 'POST':
        diagnostico = getDiagnostico(request)

        if diagnostico is not None:
            messages.add_message(request, messages.SUCCESS, 'Diagnostico creado con exito!')
        else:
            messages.add_message(request, messages.WARNING, 'Error inesperado creando diagnostico!')
        return redirect('diagnostico:ListarDiagnosticos')

    try:
        pacientes = Paciente.objects.filter(usuario__estado='A', pacientepersonal__estado='A',
                                            pacientepersonal__personal_id=sesion.get('personal__id', 0))\
            .values('id', 'usuario__nombre', 'usuario__apellido') \
            .annotate(nombre_completo=Concat('usuario__nombre', Value(' '), 'usuario__apellido')) \
            .order_by('nombre_completo')
        if pacientes is None or pacientes.count() == 0:
            raise Exception
    except Exception, e:
        messages.add_message(request, messages.WARNING, 'No tiene pacientes asignados, consulte con su administrador! ')

    contexto['pacientes'] = pacientes

    if rol == 'fisioterapista':
        template = 'diagnostico_crear.html'
    elif rol == 'nutricionista':
        template = 'diagnostico_nut_crear.html'
        contexto['dias'] = DIAS
    else:
        return redirect(to='/')

    return render(request, template_name=template, context=contexto)

'''
Funcion: getDiagnostico
Entradas: - request
Salidas:  - nueva diagnostico

Funcion que retorna un nuevo diagnostico con los datos ingresados en formulario
'''


@transaction.atomic
def getDiagnostico(request):
    diagnostico = None
    sesion = request.session.get('user_sesion', None)
    rol = None

    if sesion:
        rol = sesion.get('rol__tipo', None)

    if rol is not None:
        try:
            if rol == 'fisioterapista':
                diagnostico = DiagnosticoFisioterapia()
                diagnostico.area_afectada = request.POST.get('areaafectada', '')
                diagnostico.receta = request.POST.get('receta', '')
                diagnostico.rutina = Rutina.objects.create()

                cantidad_rutinas = int(request.POST.get('cantidadrutinas', '0'))
                id_rutinas = request.POST.getlist('idaccordion', [])
                nombre_rutinas = request.POST.getlist('nombrerutina', [])
                descripcion_rutinas = request.POST.getlist('descripcionrutina', [])
                repeticiones_rutinas = request.POST.getlist('repeticionesrutina', [])
                veces_rutinas = request.POST.getlist('vecesrutina', [])
                descanso_rutinas = request.POST.getlist('descansorutina', [])
                videoenlace_rutinas = request.POST.getlist('videoenlace', [])

                for id, nom, desc, rep, vec, des, vid in zip(id_rutinas, nombre_rutinas, descripcion_rutinas,
                                                             repeticiones_rutinas, veces_rutinas, descanso_rutinas,
                                                             videoenlace_rutinas):

                    subrutina = Subrutina.objects.create(nombre=nom, detalle=desc, repeticiones=rep, veces=vec,
                                                         descanso=des, link=vid)
                    diagnostico.rutina.subrutina.add(subrutina)
            elif rol == 'nutricionista':
                diagnostico = DiagnosticoNutricion()

                dieta = Dieta()
                dieta.descripcion = request.POST.get('dietadescripcion', '')
                dieta.save()
                diagnostico.dieta = dieta

                for key, dia in DIAS:
                    plan_diario = PlanNutDiario(dia=dia,
                                                desayuno=request.POST.get(dia+'_Desayuno', ''),
                                                colacion1=request.POST.get(dia+'_Colacion1', ''),
                                                almuerzo=request.POST.get(dia+'_Almuerzo', ''),
                                                colacion2=request.POST.get(dia+'_Colacion2', ''),
                                                cena=request.POST.get(dia+'_Cena', ''),
                                                dieta=dieta)
                    plan_diario.save()

            diagnostico.personal = Personal.objects.get(estado='A', id=sesion.get('personal__id', 0))
            diagnostico.paciente = Paciente.objects.get(estado='A', id=request.POST.get('paciente', 0))
            diagnostico.condiciones_previas = request.POST.get('condicionesprevias', '')
            diagnostico.save()
        except Exception, e:
            return None
    return diagnostico

'''
Funcion: crearDiagnostico
Entradas: - request
          - id: id del diagnostico a eliminar
Salidas: ninguna

Funcion que permite eliminar un diagnostico existente
'''


@login_required
@rol_required(roles=['fisioterapista', 'nutricionista'])
@transaction.atomic
def eliminarDiagnostico(request, id=0):
    contexto = {}
    diagnosticoEliminado = None
    sesion = request.session.get('user_sesion', None)

    if sesion:
        rol = sesion.get('rol__tipo', None)

    if request.method == 'POST':
        try:
            if rol == 'fisioterapista':
                diagnosticoEliminado = DiagnosticoFisioterapia.objects.get(estado='A', id=id)
                subrutinas = Subrutina.objects.filter(rutina=diagnosticoEliminado.rutina)
                for subrutina in subrutinas:
                    subrutina.estado = 'I'
                    subrutina.save()
                diagnosticoEliminado.rutina.estado = 'I'
                diagnosticoEliminado.rutina.save()

            elif rol == 'nutricionista':
                diagnosticoEliminado = DiagnosticoNutricion.objects.get(estado='A', id=id)
                diagnosticoEliminado.dieta.estado = 'I'
                diagnosticoEliminado.dieta.save()

                for plan_diario in PlanNutDiario.objects.filter(estado='A', dieta=diagnosticoEliminado.dieta):
                    plan_diario.estado = 'I'
                    plan_diario.save()

            if diagnosticoEliminado and diagnosticoEliminado.estado == 'A':
                diagnosticoEliminado.estado = 'I'
                diagnosticoEliminado.save()
                messages.add_message(request, messages.SUCCESS, 'Diagnostico eliminado con exito!')
            else:
                messages.add_message(request, messages.WARNING, 'Diagnostico no encontrado o ya eliminado')
        except Exception, e:

diagnostico/templates/diagnostico.html
{%  extends 'blank.html' %}
{% load staticfiles %}
{% block title %}Diagnósticos{% endblock %}

{% block content %}


    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                    {% if messages %}
                        <div class="row messages">
                        {% for message in messages %}
                            <div {% if message.tags %} class="alert alert-{{ message.tags }} fade in alert-dismissable"{% endif %} style="margin-left:18px;">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">&times;</a>
                                <strong>{{ message }}</strong>
                            </div>
                        {% endfor %}
                        </div>
                    {% endif %}
                    <div class="panel panel-default" style="margin-top: 40px">
                    <div class="panel-heading"><h4><b>Últimos diagn&oacute;sticos</b></h4></div>
                        <div class="panel-body">
                            <table class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline collapsed table-responsive vertical-align" width="100%">
                                    <thead class="thead-inverse">
                                    <tr>
                                        <th class="text-center sorting">ID</th>
                                        <th class="text-center sorting">Paciente</th>
                                        <th class="text-center sorting">Registro</th>
                                        <th class="text-center sorting">Actualizado</th>
                                        <th class="text-center">Editar</th>
                                        <th class="text-center">Eliminar</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% if diagnosticos %}
                                        {% for diagnostico in diagnosticos %}
                                                <tr>
                                                    <td>{{diagnostico.id}}</td>
                                                    <td>{{ diagnostico.paciente_nombre_completo}}</td>
                                                    <td>{{ diagnostico.creado}}</td>
                                                    <td>{{ diagnostico.actualizado}}</td>
                                                    <td class="text-center">
                                                        <!-- Editar diagnostico-->
                                                        <form action="{% url 'diagnostico:EditarDiagnostico' diagnostico.id %}" method="post" style="display: inline;">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="diagnostico_id" value="{{ diagnostico.id }}" />
                                                            <button type="submit" class="btn btn-sm btn-info">
                                                                <span class="glyphicon glyphicon-edit"></span>
                                                            </button>
                                                        </form>
                                                    </td>
                                                    <td class="text-center">
                                                            <!-- Eliminar diagnostico-->
                                                            <form action="{% url 'diagnostico:EliminarDiagnostico' diagnostico.id %}" method="post" style="display: inline;">
                                                                {% csrf_token %}
                                                                <input type="hidden" name="diagnostico_id" value="{{ diagnostico.id }}" />
                                                                <button type="submit" class="btn btn-sm btn-danger">
                                                                    <span class="glyphicon glyphicon-trash"></span>
                                                                </button>
                                                            </form>
                                                        </td>
                                                </tr>

                                        {% endfor %}
                                    {% else %}
                                        <tr>
                                            <td align="center" colspan="7">Sin informaci&oacute;n</td>
                                        </tr>
                                    {% endif %}
                                    </tbody>
                                </table>
                                {% if diagnosticos_paginator and diagnosticos_paginator.has_other_pages %}
                                      <ul class="pagination">
                                        {% if diagnosticos_paginator.has_previous %}
                                          <li><a href="?pag={{ diagnosticos_paginator.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                          <li class="disabled"><span>&laquo;</span></li>
                                        {% endif %}
                                        {% for i in diagnosticos_paginator.paginator.page_range %}
                                          {% if diagnosticos_paginator.number == i %}
                                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                          {% else %}
                                            <li><a href="?pag={{ i }}">{{ i }}</a></li>
                                          {% endif %}
                                        {% endfor %}
                                        {% if diagnosticos_paginator.has_next %}
                                          <li><a href="?pag={{ diagnosticos_paginator.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                          <li class="disabled"><span>&raquo;</span></li>
                                        {% endif %}
                                      </ul>
                                {% endif %}
                        </div>
                    </div></div></div></div></div>
{% endblock %}

diagnostico/templates/diagnostico_listar.html
{%  extends 'blank.html' %}
{% load staticfiles %}
{% block title %}Diagnósticos{% endblock %}

{% block content %}


    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                    {% if messages %}
                        <div class="row messages">
                        {% for message in messages %}
                            <div {% if message.tags %} class="alert alert-{{ message.tags }} fade in alert-dismissable"{% endif %} style="margin-left:18px;">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">&times;</a>
                                <strong>{{ message }}</strong>
                            </div>
                        {% endfor %}
                        </div>
                    {% endif %}
                    <div class="panel panel-default" style="margin-top: 40px">
                    <div class="panel-heading"><h4><b>Últimos diagn&oacute;sticos</b></h4></div>
                        <div class="panel-body">
                            <table class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline collapsed table-responsive vertical-align" id="dataTables-example" width="100%">
                                    <thead class="thead-inverse">
                                    <tr>
                                        <th class="text-center sorting">Detalle</th>
                                        <th class="text-center sorting">Paciente</th>
                                        <th class="text-center sorting">C&eacute;dula</th>
                                        <th class="text-center sorting">Registro</th>
                                        <th class="text-center sorting">Actualizado</th>
                                        <th class="text-center">Editar</th>
                                        <th class="text-center">Eliminar</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% if diagnosticos %}
                                        {% for diagnostico in diagnosticos %}
                                                <tr>
                                                    <td style="text-align: center;"><a href="{% url 'diagnostico:detail' diagnostico.id %}"><button type="submit" class="btn btn-default">
                                                    <span class="glyphicon glyphicon-eye-open"></span>
                                                    </button></a></td>
                                                    <td>
                                                        <img src="{% static diagnostico.paciente_foto %}" class="img-circle" height="50px" width="50px"/>
                                                        &nbsp;&nbsp;&nbsp;{{ diagnostico.paciente_nombre_completo }}
                                                    </td>
                                                    <td>{{ diagnostico.cedula}}</td>
                                                    <td>{{ diagnostico.creado}}</td>
                                                    <td>{{ diagnostico.actualizado}}</td>
                                                    <td class="text-center">
                                                        <!-- Editar diagnostico-->
                                                        <form action="{% url 'diagnostico:EditarDiagnostico' diagnostico.id %}" method="post" style="display: inline;">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="diagnostico_id" value="{{ diagnostico.id }}" />
                                                            <button type="submit" class="btn btn-sm btn-info">
                                                                <span class="glyphicon glyphicon-edit"></span>
                                                            </button>
                                                        </form>
                                                    </td>
                                                    <td class="text-center">
                                                        <form action="{% url 'diagnostico:EliminarDiagnostico' diagnostico.id %}" method="post" style="display: inline;">
                                                                {% csrf_token %}
                                                                <input type="hidden" name="diagnostico_id" value="{{ diagnostico.id }}" />
                                                                <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#eliminardiagnostico"> <!--submit-->
                                                                    <span class="glyphicon glyphicon-trash"></span>
                                                                </button>
                                                        </form>
                                                    </td>
                                                </tr>

                                        {% endfor %}
                                    {% else %}
                                        <tr>
                                            <td align="center" colspan="7">Sin informaci&oacute;n</td>
                                        </tr>
                                    {% endif %}
                                    </tbody>
                                </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal Dialog -->
        <div class="modal fade" id="eliminardiagnostico" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Eliminar permanentemente</h4>
              </div>
              <div class="modal-body">
                <p>¿Est&aacute; seguro de eliminar el diagn&oacute;stico?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger" id="confirm">Eliminar</button>
              </div>
            </div>
          </div>
        </div>
    </div>
{% endblock %}
{% block scriptDown %}
    <!-- Dialog show event handler -->
    <script type="text/javascript">
      $('#eliminardiagnostico').on('show.bs.modal', function (e) {
          $message = $(e.relatedTarget).attr('data-message');
          $(this).find('.modal-body p').text($message);
          $title = $(e.relatedTarget).attr('data-title');
          $(this).find('.modal-title').text($title);

          // Pass form reference to modal for submission on yes/ok
          var form = $(e.relatedTarget).closest('form');
          $(this).find('.modal-footer #confirm').data('form', form);
      });

      <!-- Form confirm (yes/ok) handler, submits form -->
      $('#eliminardiagnostico').find('.modal-footer #confirm').on('click', function(){
          $(this).data('form').submit();
      });
    </script>
{% endblock %}