fisioterapia/urls.py
from django.conf.urls import url

from . import views

app_name = 'fisioterapia'
urlpatterns = [
    url(r'^$', views.index, name="indexF"),
    url(r'^ficha/$', views.crear_ficha, name="crear_ficha"),
    url(r'^ficha/lista/$', views.listar_fichas, name="lista_fichas"),
    url(r'^(?P<ficha_id>[0-9]+)/$', views.detalleFicha, name='detail'),
    #url(r'^mensajes/$', views.verMensajes, name='mensajesF'),
    #url(r'^mensajes/nuevo/$', views.nuevoMensaje, name='nuevoMensajeF'),
    #url(r'^mensajes/leer/(?P<mensaje_id>[0-9]+)/$', views.leerMensaje, name='leerMensajeF'),
    url(r'(?P<ficha_id>[0-9]+)/eliminar/$', views.eliminar_ficha, name="eliminar_ficha"),
    url(r'^editar/(?P<ficha_id>[0-9]+)/$', views.editar_ficha, name='editar_ficha'),
    url(r'^horario/$', views.establecer_horario, name="crear_horario"),
    url(r'^horario/ver/$', views.ver_horarios, name="ver_horarios"),
    url(r'(?P<horario_id>[0-9]+)/cita/eliminar/$', views.eliminar_cita, name="eliminar_cita"),
    url(r'^reportes/$', views.reportes, name="reportes"),
    url(r'^reporte/ficha/(?P<paciente_cedula>[0-9]+)/$', views.reporteFicha),
    url(r'^reporte/fichas/$', views.reporte)
]

kala/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import login, logout, password_change, password_change_done, password_reset, \
                                        password_reset_done, password_reset_complete, password_reset_confirm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm

urlpatterns = [
    url(r'^', include('kalaapp.urls')),
    url(r'^api/', include('clienteRest.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^paciente/', include('paciente.urls')),
    url(r'^personal/', include('personal.urls')),
    url(r'^factura/', include('factura.urls')),
    url(r'^fisioterapia/', include('fisioterapia.urls')),
    url(r'^nutricion/', include('nutricion.urls')),
    url(r'^diagnostico/', include('diagnostico.urls')),

    url(r'^login/$', login, 
        {'template_name': 'login.html', 'authentication_form': AuthenticationForm, 'redirect_authenticated_user': True}, 
        name='login'),
    url(r'^logout/$', logout, 
        {'next_page': settings.LOGIN_URL}, 
        name="logout"),
    url(r'^password_change/$', password_change,
        {'template_name': 'password_change.html', 'password_change_form': PasswordChangeForm}, 
        name='password_change'),
    url(r'^password_change/done/$', password_change_done, 
        {'template_name': 'password_change_done.html'},
        name='password_change_done'),
    url(r'^password_reset/$', password_reset,
        {'template_name': 'password_reset.html',
         'password_reset_form': PasswordResetForm},
        name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done,
        {'template_name': 'password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, 
        {'template_name': 'password_reset_confirm.html', 'set_password_form': SetPasswordForm},
        name='password_reset_confirm'),
    url(r'reset/done/$', password_reset_complete, 
        {'template_name': 'password_reset_complete.html'},
        name='password_reset_complete'),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

kalaapp/urls.py
'''
Created on Jun 4, 2017

@author: carlos
'''
from django.conf.urls import url

from . import views

app_name = 'kalaapp'

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^asignar$', views.asignarPersonalaPaciente, name="AsignarPersonalaPaciente"),
]

paciente/urls.py
from django.conf.urls import url
#from paciente.views import reportePDF, reportePacientes
from . import views

app_name = 'paciente'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^crear/$', views.PacienteNuevo, name="paciente"),
    url(r'^(?P<paciente_id>[0-9]+)/$', views.detallePaciente, name='detail'),
    url(r'^editar/(?P<paciente_id>[0-9]+)/$', views.editarPaciente, name='editar'),
    #url(r'^modificar/(?P<paciente_id>\d+)/$', views.PacienteModificar, name="modificar"),
    url(r'^eliminar/(?P<paciente_id>\d+)/', views.PacienteEliminar, name="eliminar"),
    url(r'^reporte/hombres/$', views.reporteHombres),
    url(r'^reporte/mujeres/$', views.reporteMujeres),
    url(r'^reporte/totales/$', views.reporteTotales),
    url(r'^reportes/$', views.reportes, name="reportes"),
]

personal/urls.py
from django.conf.urls import url
from . import views


app_name = 'personal'

urlpatterns = [
    url(r'^$', views.index , name="index"),
    url(r'^crear/$', views.nuevoPersonal, name="nuevoPersonal"),
    #url(r'^modificar/(?P<paciente_id>\d+)/$', views.modificarPersonal, name="modificarPersonal"),
    url(r'(?P<personal_id>[0-9]+)/eliminar/$', views.eliminarPersonal, name="eliminarPersonal"),
    url(r'^(?P<personal_id>[0-9]+)/$', views.detallePersonal, name='detail'),
    url(r'^editar/(?P<personal_id>[0-9]+)/$', views.editarPersonal, name='editar'),
    url(r'^mensajes/$', views.verMensajes, name='mensajes'),
    url(r'^mensajes/nuevo/paciente$', views.nuevoMensajePaciente, name='nuevoMensaje'),
    url(r'^mensajes/nuevo/personal$', views.nuevoMensajePersonal, name='nuevoMensajePersonal'),
    url(r'^mensajes/leer/(?P<mensaje_id>[0-9]+)/$', views.leerMensaje, name='leerMensaje'),
    url(r'^reportes/$', views.reportes, name="reportes"),
    url(r'^reporte/total/$', views.reporteTotal),
    url(r'^reporte/rol/$', views.reporteRol),
    url(r'^reporte/mujeres/$', views.reporteMujeres),
    url(r'^reporte/hombres/$', views.reporteHombres),
]

fisioterapia/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

#from time import timezone

from django.db import models
from kalaapp.models import TimeModel
from personal.models import Personal
from paciente.models import Paciente
#from django.utils.timezone import  now
from django.utils import timezone
import datetime
# Create your models here.

TIPO =(('alta', 'Alta'),
        ('media', 'Media'),
        ('baja', 'Baja'))

ESTADO = (('1', 'No tomada'),
          ('2', 'Finalizada'))


class Ficha(TimeModel):
    personal = models.ForeignKey(Personal, on_delete=models.DO_NOTHING)
    paciente = models.ForeignKey(Paciente, on_delete=models.DO_NOTHING)

    #estado = models.OneToOneField('EstadoFisico', on_delete=models.CASCADE, unique=True)
    #fecha = models.DateField(default=timezone.now, blank=False, null=False)
    altura = models.FloatField(null=True)
    peso = models.FloatField(null=True)
    imc = models.FloatField(null=True)
    musculo = models.FloatField(null=True)
    grasa_visceral = models.FloatField(null=True)
    grasa_porcentaje = models.FloatField(null=True)
    cuello = models.FloatField(null=True)
    hombros = models.FloatField(null=True)
    pecho = models.FloatField(null=True)
    brazo_derecho = models.FloatField(null=True)
    brazo_izquierdo = models.FloatField(null=True)
    antebrazo_derecho = models.FloatField(null=True)
    antebrazo_izquierdo = models.FloatField(null=True)
    cintura = models.FloatField(null=True)
    cadera = models.FloatField(null=True)
    muslo_derecho = models.FloatField(null=True)
    muslo_izquierdo = models.FloatField(null=True)
    pantorrilla_derecha = models.FloatField(null=True)
    pantorrilla_izquierda = models.FloatField(null=True)

    # duration = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    flexiones = models.PositiveSmallIntegerField(default=1, null=False)
    sentadillas = models.PositiveSmallIntegerField(default=1, null=False)
    saltoLargo = models.PositiveSmallIntegerField(default=1, null=False)
    suspension = models.CharField(max_length=200, choices=TIPO, default='baja', null=False)
    abdomen_bajo = models.PositiveSmallIntegerField(default=1, null=False)
    abdomen_alto = models.PositiveSmallIntegerField(default=1, null=False)
    espinales = models.PositiveSmallIntegerField(default=1, null=False)
    lumbares = models.PositiveSmallIntegerField(default=1, null=False)
    trenSuperior = models.TimeField(blank=True, default=datetime.time(00, 00))
    trenInferior = models.TimeField( blank=True, default=datetime.time(00,00))

    class Meta:
        #managed = False
        db_table = 'ficha'

class Horario(TimeModel):
    personal = models.ForeignKey(Personal, on_delete=models.DO_NOTHING)
    paciente = models.ForeignKey(Paciente, on_delete=models.DO_NOTHING, null=True, blank=True)

    fecha = models.DateField(auto_now=False)
    hora = models.TimeField(auto_now=False)
    duracion = models.PositiveSmallIntegerField(default=10, null=False)
    detalle = models.CharField(max_length=200, null=False)
    estado = models.CharField(max_length=200, choices=ESTADO, default='1', null=False)

    class Meta:
        db_table = 'horario_fis'

fisioterapia/forms.py
from django import forms
from django.forms import NumberInput, ModelForm, Select, TextInput, DateField, DateInput, Textarea
from django.forms.extras.widgets import  SelectDateWidget
from datetimewidget.widgets import DateTimeWidget, TimeWidget, DateWidget


from paciente.models import Paciente
from kalaapp.models import Usuario, Rol
from django.contrib.auth.models import User
from fisioterapia.models import Ficha, Horario



class ComentarioForm(forms.Form):
     Destino= forms.ModelMultipleChoiceField(queryset=Paciente.objects.all())
     comentario = forms.CharField(widget=forms.Textarea)

class DateTypeInput(forms.DateInput):
    input_type = 'date'

class HorariosForm(ModelForm):
    class Meta:
        model = Horario
        fields = [ 'fecha', 'hora', 'detalle', 'estado', 'duracion' ]
        labels = {'fecha':'Fecha', 'hora': 'Hora', 'detalle': 'Detalle', 'estado': 'Estado', 'duracion': 'Duracion(Minutos)'}
        widgets = {
            'fecha': DateWidget(attrs={'id':"yourdatetimeid", 'class': u'form-control'}, usel10n = True, bootstrap_version=3),
            'hora': TimeWidget(attrs={'id':"yourdatetimeid", 'class': u'form-control'}, usel10n = True, bootstrap_version=3),
            'detalle': Textarea(
                attrs={'class': u'form-control', 'placeholder': u'Ingrese respuesta ...', 'rows': 10, 'cols': 40,
                       'style': 'height: 6em;'}),
            'estado': Select(attrs={'class': u'form-control'}),
            'duracion': NumberInput(
                attrs={'class': u'form-control', 'placeholder': u'Minutos', 'min': '1', 'max': '120',
                       'step': '5'}),
                   }

class FichaForm(ModelForm):
    class Meta:
         model = Ficha

         fields = [#'fecha',
                   'altura', 'peso', 'imc', 'musculo', 'grasa_visceral', 'grasa_porcentaje',
                   'cuello', 'hombros', 'pecho', 'brazo_derecho', 'brazo_izquierdo', 'antebrazo_derecho',
                   'antebrazo_izquierdo', 'cintura', 'cadera', 'muslo_derecho', 'muslo_izquierdo',
                   'pantorrilla_derecha', 'pantorrilla_izquierda', 'flexiones', 'sentadillas', 'saltoLargo',
                   'suspension', 'abdomen_bajo', 'abdomen_alto', 'espinales', 'lumbares', 'trenSuperior', 'trenInferior'
                   ]
         labels = {
              'altura': 'Altura', 'peso': 'Peso', 'imc': 'Imc', 'musculo': 'Musculo',
              'grasa_visceral': 'Grasa Viseral', 'grasa_porcentaje': 'Grasa Porcentual', 'cuello': 'Cuello',
              'hombros': 'Hombros', 'pecho': 'Pecho', 'brazo_derecho':  'Brazo Derecho', 'brazo_izquierdo': 'Brazo Izquierdo', 'antebrazo_derecho': 'Antebrazo Derecho',
                  'antebrazo_izquierdo': 'Antebrazo Izquierdo', 'cintura': 'Cintura', 'cadera': 'Cadera', 'muslo_derecho': 'Muslo Derecho', 'muslo_izquierdo': 'Muslo Izquierdo',
                  'pantorrilla_derecha': 'Pantorilla Derecha', 'pantorrilla_izquierda': 'Pantorilla Izquierda', 'flexiones': 'Flexiones', 'sentadillas': 'Sentadillas', 'saltoLargo': 'Salto Largo',
                  'suspension': 'Suspension', 'abdomen_bajo': 'Abdomen Bajo', 'abdomen_alto': 'Abdomen Alto', 'espinales': 'Espinales', 'lumbares': 'Lumbares',
                  'trenSuperior': 'Tren Superior', 'trenInferior': 'Tren Inferior',
         }
         widgets = {
             #'fecha': DateTypeInput(attrs={'class': u'form-control'}),
             'altura': NumberInput(attrs={'class': u'form-control', 'placeholder': u'Altura en centimetros', 'min': '1.0', 'step': '0.1'}),
             'peso': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Peso en Kilogramos', 'min': '1.0',
                        'step': '0.1'}),
             'imc': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Indice de masa corporal', 'min': '1.0',
                        'step': '0.1'}),
             'musculo': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Porcentaje muscular', 'min': '1.0',
                        'step': '0.1'}),
             'grasa_visceral': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Grasa visceral', 'min': '1.0',
                        'step': '0.1'}),
             'grasa_porcentaje': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Altura en centimetros', 'min': '1.0',
                        'step': '0.1'}),
             'cuello': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Cuello', 'min': '1.0',
                        'step': '0.1'}),
             'hombros': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Hombros', 'min': '1.0',
                        'step': '0.1'}),
             'pecho': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'pecho', 'min': '1.0',
                        'step': '0.1'}),
             'brazo_derecho': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Brazo Derecho', 'min': '1.0',
                        'step': '0.1'}),
             'brazo_izquierdo': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Brazo izquierdo', 'min': '1.0',
                        'step': '0.1'}),
             'antebrazo_derecho': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Antebrazo derecho', 'min': '1.0',
                        'step': '0.1'}),
             'antebrazo_izquierdo': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Antebrazo izquierdo', 'min': '1.0',
                        'step': '0.1'}),
             'cintura': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Cintura', 'min': '1.0',
                        'step': '0.1'}),
             'cadera': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Cadera', 'min': '1.0',
                        'step': '0.1'}),
             'muslo_derecho': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Muslo Derecho', 'min': '1.0',
                        'step': '0.1'}),
             'muslo_izquierdo': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Muslo Izquierdo', 'min': '1.0',
                        'step': '0.1'}),
             'pantorrilla_derecha': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Pantorrilla derecha', 'min': '1.0',
                        'step': '0.1'}),
             'pantorrilla_izquierda': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Pantorrilla izquierda', 'min': '1.0',
                        'step': '0.1'}),
             'flexiones': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'flexiones', 'min': '1',
                        'step': '1'}),
             'sentadillas': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Sentadillas', 'min': '1',
                        'step': '1'}),
             'saltoLargo': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Salto Largo', 'min': '1',
                        'step': '1'}),
             'abdomen_alto': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Abdomen Alto', 'min': '1',
                        'step': '1'}),
             'abdomen_bajo': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Abdomen Bajo', 'min': '1',
                        'step': '1'}),
             'espinales': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Espinales', 'min': '1',
                        'step': '1'}),
             'lumbares': NumberInput(
                 attrs={'class': u'form-control', 'placeholder': u'Lumbares', 'min': '1',
                        'step': '1'}),
             'suspension':  Select(attrs={'class': u'form-control'}),
             'trenInferior': TextInput(attrs={'class': u'form-control','placeholder': u'Ingresar Hora'}),
             'trenSuperior': TextInput(attrs={'class': u'form-control', 'placeholder': u'Ingresar Hora'}),
         }

fisioterapia/templates/fisioterapia/leerMensaje.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mensajes{% endblock %}</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'personal/style.css' %}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <style>
.alert-message
{
    margin: 20px 0;
    padding: 20px;
    border-left: 3px solid #eee;
}
.alert-message h4
{
    margin-top: 0;
    margin-bottom: 5px;
}
.alert-message p:last-child
{
    margin-bottom: 0;
}
.alert-message code
{
    background-color: #fff;
    border-radius: 3px;
}
.alert-message-success
{
    background-color: #F4FDF0;
    border-color: #3C763D;
}
.alert-message-success h4
{
    color: #3C763D;
}
.alert-message-danger
{
    background-color: #fdf7f7;
    border-color: #d9534f;
}
.alert-message-danger h4
{
    color: #d9534f;
}
.alert-message-warning
{
    background-color: #fcf8f2;
    border-color: #f0ad4e;
}
.alert-message-warning h4
{
    color: #f0ad4e;
}
.alert-message-info
{
    background-color: #f4f8fa;
    border-color: #5bc0de;
}
.alert-message-info h4
{
    color: #5bc0de;
}
.alert-message-default
{
    background-color: #EEE;
    border-color: #B4B4B4;
}
.alert-message-default h4
{
    color: #000;
}
.alert-message-notice
{
    background-color: #FCFCDD;
    border-color: #BDBD89;
}
.alert-message-notice h4
{
    color: #444;
}

    </style>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'fisioterapia:index' %}">kala App</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'fisioterapia:mensajes' %}">
                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;Inbox
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'fisioterapia:nuevoMensaje' %}">
                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;Nuevo Mensaje
                    </a>
                </li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4 col-md-4"></div>
        <div class="col-sm-4 col-md-4">
            <div class="alert-message alert-message-info">
                <h4>
                    Mensaje de {{sender}}</h4>
                <p>{{mensaje}}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

fisioterapia/templates/fisioterapia/lista-fichas.html
{%  extends 'blank.html' %}
{% load staticfiles %}
{% block title %}Fisioterapia - Ficha Medica{% endblock %}

{% block content %}
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Fichas Medicas</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                           Lista de fichas medicas de los pacientes
                        </div>
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>Detalle</th>
                                        <th>Foto</th>
                                        <th>Nombre </th>
                                        <th>Apellido</th>
                                        <th>Fecha</th>
                                        <th>IMC</th>
                                        <th>Editar</th>
                                        <th>Eliminar</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if fichas %}
                                        {% for ficha in fichas %}
                                            <tr class="">
                                                <td style="text-align: center;"><a href="{% url 'fisioterapia:detail' ficha.id %}"><button type="submit" class="btn btn-default">
                                                    <span class="glyphicon glyphicon-eye-open"></span>
                                                    </button></a></td>
                                                <td><img src="/static/{{ ficha.paciente.usuario.foto }}" class="img-responsive" height="50px" width="50px"/></td>
                                                <td class="capitalize">{{ ficha.paciente.usuario.nombre }}</td>
                                                <td class="capitalize">{{ ficha.paciente.usuario.apellido }}</td>
                                                <td>{{ ficha.creado }}</td>
                                                <td>{{ ficha.imc }}</td>
                                                <td style="text-align: center;"><a href="{% url 'fisioterapia:editar_ficha' ficha.id %}">
                                                    <button type="submit" class="btn btn-info">
                                                        <p class="fa fa-edit "></p>
                                                    </button>
                                                </a></td>
                                                <td style="text-align: center;"><a href="{%  url 'fisioterapia:eliminar_ficha' ficha.id %}">
                                                    <button type="submit" class="btn btn-danger">
                                                        <span class="glyphicon glyphicon-remove"></span>
                                                    </button>
                                                   </a></td>
                                            </tr>
                                        {% endfor %}
                                    {% endif %}
                                </tbody>
                            </table>
                            <!-- /.table-responsive -->
                        </div>
                    </div>
                    <!-- /.panel -->
                </div>
            </div>
    </div>

{% endblock %}

fisioterapia/templates/fisioterapia/mensajes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mensajes{% endblock %}</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'personal/style.css' %}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'kalaapp:home' %}">kala App</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'personal:nuevoMensaje' %}">
                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;Nuevo Mensaje
                    </a>
                </li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            {% for m in mensajes %}
             <div class="list-group">
                 {% for u in usuarios %}
                    {% if u.usuario == m.sender %}
                 <a href="{% url 'personal:leerMensaje' m.pk %}" class="list-group-item"> <span class="glyphicon glyphicon-envelope"> Mensaje de {{ u.nombre }} {{ u.apellido }}</span></a>
                    {% endif %}
                 {% endfor %}
             </div>
            {% endfor %}

        </div>
        <div class="col-sm-4"></div>
    </div>


</div>
{% endblock %}