kala/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import login, logout, password_change, password_change_done, password_reset, \
                                        password_reset_done, password_reset_complete, password_reset_confirm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm

urlpatterns = [
    url(r'^', include('kalaapp.urls')),
    url(r'^api/', include('clienteRest.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^paciente/', include('paciente.urls')),
    url(r'^personal/', include('personal.urls')),
    url(r'^factura/', include('factura.urls')),
    url(r'^fisioterapia/', include('fisioterapia.urls')),
    url(r'^nutricion/', include('nutricion.urls')),
    url(r'^diagnostico/', include('diagnostico.urls')),

    url(r'^login/$', login, 
        {'template_name': 'login.html', 'authentication_form': AuthenticationForm, 'redirect_authenticated_user': True}, 
        name='login'),
    url(r'^logout/$', logout, 
        {'next_page': settings.LOGIN_URL}, 
        name="logout"),
    url(r'^password_change/$', password_change,
        {'template_name': 'password_change.html', 'password_change_form': PasswordChangeForm}, 
        name='password_change'),
    url(r'^password_change/done/$', password_change_done, 
        {'template_name': 'password_change_done.html'},
        name='password_change_done'),
    url(r'^password_reset/$', password_reset,
        {'template_name': 'password_reset.html',
         'password_reset_form': PasswordResetForm},
        name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done,
        {'template_name': 'password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, 
        {'template_name': 'password_reset_confirm.html', 'set_password_form': SetPasswordForm},
        name='password_reset_confirm'),
    url(r'reset/done/$', password_reset_complete, 
        {'template_name': 'password_reset_complete.html'},
        name='password_reset_complete'),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

paciente/urls.py
from django.conf.urls import url
#from paciente.views import reportePDF, reportePacientes
from . import views

app_name = 'paciente'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^crear/$', views.PacienteNuevo, name="paciente"),
    url(r'^(?P<paciente_id>[0-9]+)/$', views.detallePaciente, name='detail'),
    url(r'^editar/(?P<paciente_id>[0-9]+)/$', views.editarPaciente, name='editar'),
    #url(r'^modificar/(?P<paciente_id>\d+)/$', views.PacienteModificar, name="modificar"),
    url(r'^eliminar/(?P<paciente_id>\d+)/', views.PacienteEliminar, name="eliminar"),
    url(r'^reporte/hombres/$', views.reporteHombres),
    url(r'^reporte/mujeres/$', views.reporteMujeres),
    url(r'^reporte/totales/$', views.reporteTotales),
    url(r'^reportes/$', views.reportes, name="reportes"),
]

personal/urls.py
from django.conf.urls import url
from . import views


app_name = 'personal'

urlpatterns = [
    url(r'^$', views.index , name="index"),
    url(r'^crear/$', views.nuevoPersonal, name="nuevoPersonal"),
    #url(r'^modificar/(?P<paciente_id>\d+)/$', views.modificarPersonal, name="modificarPersonal"),
    url(r'(?P<personal_id>[0-9]+)/eliminar/$', views.eliminarPersonal, name="eliminarPersonal"),
    url(r'^(?P<personal_id>[0-9]+)/$', views.detallePersonal, name='detail'),
    url(r'^editar/(?P<personal_id>[0-9]+)/$', views.editarPersonal, name='editar'),
    url(r'^mensajes/$', views.verMensajes, name='mensajes'),
    url(r'^mensajes/nuevo/paciente$', views.nuevoMensajePaciente, name='nuevoMensaje'),
    url(r'^mensajes/nuevo/personal$', views.nuevoMensajePersonal, name='nuevoMensajePersonal'),
    url(r'^mensajes/leer/(?P<mensaje_id>[0-9]+)/$', views.leerMensaje, name='leerMensaje'),
    url(r'^reportes/$', views.reportes, name="reportes"),
    url(r'^reporte/total/$', views.reporteTotal),
    url(r'^reporte/rol/$', views.reporteRol),
    url(r'^reporte/mujeres/$', views.reporteMujeres),
    url(r'^reporte/hombres/$', views.reporteHombres),
]

kalaapp/models.py
# -*- coding: utf-8 -*-
# Create your models here.
# 19262203
# This is an auto-generated Django model module.
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.utils.six import StringIO
from PIL import Image
from django.conf import settings
from django.contrib import messages
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

class TimeModel(models.Model):
    creado = models.DateTimeField(_('creado'), auto_now_add=True)
    actualizado = models.DateTimeField(_('actualizado'), auto_now=True)

    class Meta:
        abstract = True


class Rol(TimeModel):
    ROLES = (('administrador', 'administrador'), ('paciente', 'paciente'), ('fisioterapista', 'fisioterapista'),
             ('nutricionista', 'nutricionista'), ('invitado', 'invitado'))
    tipo = models.CharField(max_length=30, choices=ROLES, default='invitado')
    es_personal = models.BooleanField(_('es_personal'), default=False, blank=False)
    estado = models.CharField(max_length=1, default='A')

    class Meta:
        db_table = 'rol'


class Usuario(TimeModel):
    ESTADO_CIVIL = (('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado'))
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    rol = models.ForeignKey(Rol, on_delete=models.DO_NOTHING)
    nombre = models.CharField(max_length=30, blank=False, null=False)
    apellido = models.CharField(max_length=30, blank=False, null=False)
    cedula = models.CharField(max_length=10, unique=True)
    direccion = models.CharField(max_length=200, blank=True, null=True)
    telefono = models.CharField(max_length=50, blank=True, null=True)
    ocupacion = models.CharField(max_length=200, blank=True, null=True)
    genero = models.CharField(max_length=1, blank=True, null=True)
    edad = models.PositiveSmallIntegerField(blank=True, null=True)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    foto = models.ImageField(upload_to='usuario/',
                             default='usuario/noimagen.jpg', null=True,
                             blank=True, editable=True,
                             help_text="Foto")
    estado_civil = models.CharField(max_length=30, choices=ESTADO_CIVIL, default='Soltero', null=False)
    estado = models.CharField(max_length=1, default='A')
    is_anonymous = False
    is_authenticated = False

    USERNAME_FIELD = 'cedula'
    REQUIRED_FIELDS = ['rol', 'username', 'password', 'email']

    class Meta:
        db_table = 'usuario'

    def save(self, *args, **kwargs):
        if self.foto and self.foto.name.find('noimagen.jpg') == -1:
            try:
                img = Image.open(self.foto)
                width, height = img.size
                basewidth = 600
                baseheight = 600

                if img.mode != 'RGB':
                    img = img.convert('RGB')

                if width >= height and width > basewidth:
                    height_size = int((float(height) * float(basewidth / float(width))))
                    width = basewidth
                    height = height_size
                elif width < height and height > baseheight:
                    width_size = int((float(width) * float(baseheight / float(height))))
                    width = width_size
                    height = baseheight

                img = img.resize((width, height), Image.ANTIALIAS)
                output = StringIO()
                img.save(output, format='JPEG', quality=90)
                output.seek(0)
                self.foto = InMemoryUploadedFile(output, 'foto', "%s.jpg" % self.cedula, 'image/jpeg', output.len, None)
            except Exception as e:
                print str(e) + ' Error al  guardar la foto'

        super(Usuario, self).save(*args, **kwargs)


class Empresa(TimeModel):
    nombre = models.CharField(max_length=200, blank=False, null=False)
    razon_social = models.CharField(max_length=200, blank=True, null=True)
    propietario_nombre = models.CharField(max_length=200,blank=True, null=True)
    propietario_apellido = models.CharField(max_length=200,blank=True, null=True)
    ruc = models.CharField(max_length=50,blank=False, null=False)
    telefono = models.CharField(max_length=50,blank=True, null=True)
    direccion = models.CharField(max_length=200,blank=True, null=True)
    iva = models.IntegerField()
    #planificacion = models.ForeignKey('Planificaciones', models.DO_NOTHING)
    estado = models.CharField(max_length=1, default='A')

    class Meta:
        #managed = False
        db_table = 'empresa'

personal/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from kalaapp.models import TimeModel, models
from django.core.urlresolvers import  reverse
from kalaapp.models import Usuario, TimeModel


class Personal(TimeModel):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE, unique=True)
    estado = models.CharField(max_length=1, default='A')

    class Meta:
        #managed = False
        db_table = 'personal'
        unique_together = (('id', 'usuario'),)

    def __unicode__(self):
        return str(self.id)

personal/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Personal
from kalaapp.models import Usuario, Rol
from paciente.models import Paciente
'''

Formulario para la creacion de un nuevo Usuario
*Se definen los campos que seran visualizados y se definen reglas especiales para ciertos campos

'''

class UsuarioForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput, label="Email", required=True)
    n_hijos = forms.IntegerField(label ="Numero de Hijos", widget=forms.NumberInput(attrs={'min':'0', 'max':'20'}))
    observaciones = forms.CharField(widget=forms.Textarea(attrs={'max_length':'200'}), label="Observaciones", required=True)
    motivo_consulta = forms.CharField(widget=forms.Textarea(attrs={'max_length':'200'}), label="Motivo de Consulta", required = True)
    class Meta:
        model = Usuario
        fields = ['nombre', 'apellido', 'cedula', 'email', 'estado_civil', 'direccion', 'telefono', 'ocupacion',
                  'genero', 'edad', 'foto']
        CHOICES=(
            ('M', 'Masculino'),
            ('F', 'Femenino'),
            ('O', 'Otro')
        )
        widgets = {
            'edad': forms.NumberInput(attrs={'min': '0', 'max': '100'}),
            'genero': forms.Select(choices=CHOICES)
        }
'''

Formulario para la Edicion de un Usuario

'''
class UsuarioEditForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput, label="Email", required=True)
    class Meta:
        model = Usuario
        fields = ['nombre', 'apellido', 'email', 'estado_civil', 'direccion', 'telefono', 'ocupacion',
                  'genero', 'edad', 'foto']
        CHOICES = (
            ('M', 'Masculino'),
            ('F', 'Femenino'),
            ('O', 'Otro')
        )
        widgets = {
            'edad': forms.NumberInput(attrs={'min': '0', 'max': '100'}),
            'genero': forms.Select(choices=CHOICES)
        }
'''

Formulario para la creacion de un nuevo User
*Se definen los campos que seran visualizados y se definen reglas especiales para ciertos campos

'''
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(widget= forms.EmailField)

    class Meta:
        model = User
        fields = ['username', 'password', 'email']

'''

Formulario para la creacion de un nuevo Personal
*Se definen los campos que seran visualizados y se definen reglas especiales para ciertos campos

'''
class PersonalForm(forms.ModelForm):
    ROLES=(
        (1, "Fisioterapista"),
        (2, "Nutricionista"),
    )
    email = forms.EmailField(widget=forms.EmailInput, label="Email")
    ocupacion = forms.ChoiceField(choices=ROLES, required=True)
    class Meta:
        model = Usuario
        fields = ['nombre', 'apellido', 'cedula', 'email', 'estado_civil', 'direccion', 'telefono', 'ocupacion',
                  'genero', 'edad', 'foto']
        CHOICES = (
            ('M', 'Masculino'),
            ('F', 'Femenino'),
            ('O', 'Otro')
        )
        widgets = {
            'edad': forms.NumberInput(attrs={'min': '0', 'max': '100'}),
            'genero': forms.Select(choices=CHOICES)
        }
'''

Formulario para la creacion de un Mensaje


'''
class ComentarioForm(forms.Form):
    CHOICES = Paciente.objects.all()
    C=[]
    for p in CHOICES:
        if p.usuario.estado !="I":
            C.append(p)
    Destino = forms.ChoiceField(choices=((x.usuario.id, x.usuario.nombre +" "+ x.usuario.apellido) for x in C))
    mensaje = forms.CharField(widget=forms.Textarea)
'''

Formulario para la creacion de un nuevo Mensaje


'''
class ComentarioPersonalForm(forms.Form):
    CHOICES = Personal.objects.all()
    C=[]
    for p in CHOICES:
        if p.usuario.estado !="I":
            C.append(p)

    Destino = forms.ChoiceField(choices=((x.usuario.id, x.usuario.nombre +" "+ x.usuario.apellido) for x in C))
    mensaje = forms.CharField(widget=forms.Textarea)
'''

Formulario para la Edicion de un Personal


'''
class PersonalEditForm(forms.ModelForm):
    ROLES=(
        (1, "Fisioterapista"),
        (2, "Nutricionista"),
    )
    email = forms.EmailField(widget=forms.EmailInput, label="Email")
    ocupacion = forms.ChoiceField(choices=ROLES, required=True)
    class Meta:
        model = Usuario
        fields = ['nombre', 'apellido', 'email', 'estado_civil', 'direccion', 'telefono', 'ocupacion',
                  'genero', 'edad', 'foto']
        CHOICES = (
            ('M', 'Masculino'),
            ('F', 'Femenino'),
            ('O', 'Otro')
        )
        widgets = {
            'edad': forms.NumberInput(attrs={'min': '0', 'max': '100'}),
            'genero': forms.Select(choices=CHOICES)
        }

personal/templates/personal/form_personal.html
{% extends 'blank.html' %}
{% load l10n %}
{% block title %}{% if editar %}Editar Personal{% else %}Nuevo personal{% endif %}{% endblock %}
{% block content %}
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
             <div class="col-lg-8 col-md-8 col-xs-8 col-sm-8">
                <div class="panel panel-default" style="margin-top: 40px">
                    {% if editar %}
                        <div class="panel-heading"><h4><b>Editar Personal</b></h4></div>
                    {% else %}
                        <div class="panel-heading"><h4><b>Ingrese los datos de un nuevo personal</b></h4></div>
                    {% endif %}
                    <div class="panel-body">
                        <form class="form-vertical" action="" onsubmit="return validarCedula();" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'personal/form_template.html' %}
                            <div class="form-group">
                                {% if editar %}
                                    <button type="submit" class="btn btn-success">Editar</button>
                                {% else %}
                                    <button type="submit" class="btn btn-success">Crear personal</button>
                                {% endif %}
                            </div>
                        </form>
                    </div>
                </div>
             </div>
        </div>
    </div>
</div>
<script type="text/javascript">

function validarCedula() {
		    var cedula =  $("#id_cedula").val();
			var array = cedula.split('');

		    if ( array.length != 10 || cedula == 0000000000) {
				alert("Por favor ingrese un numero de cedula valido");
		        return false;
		    } else {
		        var total = 0;
		        var digito = (array[9]*1);

		        for(var i=0; i < (array.length-1); i++ ){
		            var mult = 0;
		            if ( ( i%2 ) !== 0 ) {
		                total = total + ( array[i] * 1 );
		            }
		            else {
		                mult = array[i] * 2;
		                if ( mult > 9 )
		                  total = total + ( mult - 9 );
		                else
		                  total = total + mult;
		            }
		        }

		        var decena = total / 10;
		        decena = Math.floor( decena );
		        decena = ( decena + 1 ) * 10;
		        var final = ( decena - total );

		        if ( ( final == 10 && digito === 0 ) || ( final == digito ) ) {
					console.log("cedula valida, segunda validacion");
		            return true;
		        } else {
		            alert("Por favor ingrese un numero de cedula valido");
					return false;
		        }
		    }
		}

    $( "#id_nombre" ).prop('required', true);
    $( "#id_apellido" ).prop('required', true);
    $( "#id_cedula" ).attr("pattern", '^[0-9]{10}').attr('title','Numero de cedula invalido').prop('required', true);
    $( "#id_direccion" ).prop('required', true);
    $( "#id_telefono" ).attr("pattern", '^[0-9]{7,10}').attr('title','Numero de telefono invalido').prop('required', true);
    $( "#id_ocupacion" ).prop('required', true);
    $( "#id_genero" ).prop('required', true); 
    $( "#id_edad" ).attr("pattern", '^[0-9]{1,2}').attr('title','Edad invalida').prop('required', true);
</script>
{% endblock %}

personal/templates/personal/form_template.html
{% load bootstrap_tags %}
{% with form_=form|as_bootstrap %}
    {% for field in form %}
        <div class="form-group">
            <span class="text-danger small"> {{ field.errors }} </span>
            {{ field.label_tag }}
            {{ field }}
        </div>
    {% endfor %}
{% endwith %}


<!--{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}-->

personal/templates/personal/index.html
{% extends 'blank.html' %}
{% load static %}
{% load l10n %}
{% block title %}Personal{% endblock %}
{% block content %}
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                    {% if messages %}
                        <div class="row messages">
                        {% for message in messages %}
                            <div {% if message.tags %} class="alert alert-{{ message.tags }} fade in alert-dismissable"{% endif %} style="margin-left:18px;">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">&times;</a>
                                <strong>{{ message }}</strong>
                            </div>
                        {% endfor %}
                        </div>
                    {% endif %}
                </div>
        <div class="panel panel-default" style="margin-top: 40px">
        <div class="panel-heading"><h4><b>Personal</b></h4></div>
        <div class="panel-body">
            <div class="container-fluid">
                <div class="row">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead class="thead-inverse">
                    <tr>
                        <th class="text-center">Detalle</th>
                        <th class="text-center">Foto</th>
                        <th class="text-center">Nombre</th>
                        <th class="text-center">Apellido</th>
                        <th class="text-center">Rol</th>
                        <th class="text-center">Direccion</th>
                        <th class="text-center">Telefono</th>
                        <th class="text-center">Cedula</th>
                        <th class="text-center">Editar</th>
                        <th class="text-center">Eliminar</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for personal in all_personal %}
                        {% if personal.rol.es_personal %}
                            <tr>
                                <td class="text-center" scope="row"><a href="{% url 'personal:detail' personal.id %}"><button type="submit" class="btn btn-default">
                                                    <span class="glyphicon glyphicon-eye-open"></span>
                                            </button></a></td>

                                {% if personal %}
                                   <td><img src="/static/{{ personal.foto }}" class="img-circle" height="50px" width="50px"/></td>
                                {% else %}
                                    <td><img src="/static/usuario/noimagen.jpg" class="img-circle" width="50px" height="50px"/></td>
                                {% endif %}
                                <td class="capitalize">{{ personal.nombre }}</td>
                                <td class="capitalize">{{ personal.apellido }}</td>
                                <td class="capitalize">{{ personal.rol.tipo}}</td>
                                <td class="capitalize">{{ personal.direccion }}</td>
                                <td>{{ personal.telefono }}</td>
                                <td>{{ personal.cedula }}</td>
                                <td  class="text-center">
                                    <a href="{% url 'personal:editar' personal.id %}">
                                        <button type="submit" class="btn btn-sm btn-info">
                                                <span class="glyphicon glyphicon-edit"></span>
                                        </button>
                                    </a>
                                </td>
                                <td class="text-center">
                                    <form action="{% url 'personal:eliminarPersonal' personal.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="personal_id" value="{{ personal.id }}" />
                                        <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#eliminarpersonal"> <!--submit-->
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </form>
                                </td>

                            </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>

        </div>
        </div>
    </div>
    <!-- Modal Dialog -->
        <div class="modal fade" id="eliminarpersonal" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Eliminar permanentemente</h4>
              </div>
              <div class="modal-body">
                <p>¿Est&aacute; seguro de eliminar el personal?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger" id="confirm">Eliminar</button>
              </div>
            </div>
            </div>
          </div>
        </div>
</div>

{% endblock %}
{% block scriptDown %}
    <!-- Dialog show event handler -->
    <script type="text/javascript">
      $('#eliminarpersonal').on('show.bs.modal', function (e) {
          $message = $(e.relatedTarget).attr('data-message');
          $(this).find('.modal-body p').text($message);
          $title = $(e.relatedTarget).attr('data-title');
          $(this).find('.modal-title').text($title);

          // Pass form reference to modal for submission on yes/ok
          var form = $(e.relatedTarget).closest('form');
          $(this).find('.modal-footer #confirm').data('form', form);
      });

      <!-- Form confirm (yes/ok) handler, submits form -->
      $('#eliminarpersonal').find('.modal-footer #confirm').on('click', function(){
          $(this).data('form').submit();
      });
    </script>
{% endblock %}

personal/templates/personal/leerMensaje.html
{% extends 'blank.html' %}
{% load l10n %}
{% block title %}Mensajes{% endblock %}
{% block content %}
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="container-fluid">
            <div class="row">
                <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h4> Mensaje de {{sender}}</h4>
                        </div>
                        <div class="panel-body">
                            <p>{{mensaje}}</p>
                        </div>
                        <div class="panel-footer">
                            {% if personal %}
                                <a href="{% url 'personal:nuevoMensajePersonal' %}"><button type="button" class="btn btn-outline btn-success btn-lg">Responder</button></a>
                            {% else %}
                                <a href="{% url 'personal:nuevoMensaje' %}"><button type="button" class="btn btn-outline btn-success btn-lg" >Responder</button></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

personal/templates/personal/mensajes.html
{% extends 'blank.html' %}
{% load l10n %}
{% block title %}Mensajes{% endblock %}
{% block content %}
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                    {% if messages %}
                        <div class="row messages">
                        {% for message in messages %}
                            <div {% if message.tags %} class="alert alert-{{ message.tags }} fade in alert-dismissable"{% endif %} style="margin-left:18px;">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">&times;</a>
                                <strong>{{ message }}</strong>
                            </div>
                        {% endfor %}
                        </div>
                    {% endif %}
                </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                    Mensajes
            </div>
                <!-- /.panel-heading -->
            <div class="panel-body">
                    <!-- Nav tabs -->
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#home" data-toggle="tab">Mensajes No leidos</a>
                    </li>
                    <li><a href="#profile" data-toggle="tab">Mensajes Leidos</a>
                    </li>
                    <li><a href="#new" data-toggle="tab">Nuevo Mensaje</a>
                    </li>
                    </ul>
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="home">
                    <h4>Mensajes No leidos</h4>
                        {% if mensajesN %}
                        <div class="col-md-8">
                            {% for m in mensajesN %}
                             <div class="list-group">
                                 {% for u in usuariosN %}
                                    {% if u.usuario == m.sender %}
                                 <a href="{% url 'personal:leerMensaje' m.pk %}" class="list-group-item"> <span class="glyphicon glyphicon-envelope"> Mensaje de {{ u.nombre }} {{ u.apellido }}</span></a>
                                    {% endif %}
                                 {% endfor %}
                             </div>
                            {% endfor %}

                        </div>
                        <div class="col-md-4"></div>
                        {% else %}
                        <div class="col-md-8">
                            <div class="alert alert-info">
                                No se encuentran mensajes que presentar
                            </div>
                        </div>
                        <div class="col-md-4"></div>
                        {% endif %}
                    </div>
                    <div class="tab-pane fade" id="profile">
                        <h4>Mensajes Leidos</h4>
                        {% if mensajesL %}

                        <div class="col-md-8">
                            {% for m in mensajesL %}
                             <div class="list-group">
                                 {% for u in usuariosL %}
                                    {% if u.usuario == m.sender %}
                                 <a href="{% url 'personal:leerMensaje' m.pk %}" class="list-group-item"> <span class="glyphicon glyphicon-envelope"> Mensaje de {{ u.nombre }} {{ u.apellido }}</span></a>
                                    {% endif %}
                                 {% endfor %}
                             </div>

                            {% endfor %}
                        </div>
                        <div class="col-md-4"></div>
                        {% else %}
                        <div class="col-md-8">
                            <div class="alert alert-info">
                                No se encuentran mensajes que presentar
                            </div>
                        </div>
                        <div class="col-md-4"></div>
                        {% endif %}
                    </div>
                    <div class="tab-pane fade" id="new">
                         <h4>Nuevo Mensaje</h4>

                        <div class="col-md-8">
                            <a href="{% url 'personal:nuevoMensajePersonal' %}"><button type="button" class="btn btn-outline btn-primary btn-lg">A Personal</button></a>
                            <a href="{% url 'personal:nuevoMensaje' %}"><button type="button" class="btn btn-outline btn-success btn-lg" >A Paciente</button></a>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}