kala/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import login, logout, password_change, password_change_done, password_reset, \
                                        password_reset_done, password_reset_complete, password_reset_confirm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm

urlpatterns = [
    url(r'^', include('kalaapp.urls')),
    url(r'^api/', include('clienteRest.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^paciente/', include('paciente.urls')),
    url(r'^personal/', include('personal.urls')),
    url(r'^factura/', include('factura.urls')),
    url(r'^fisioterapia/', include('fisioterapia.urls')),
    url(r'^nutricion/', include('nutricion.urls')),
    url(r'^diagnostico/', include('diagnostico.urls')),

    url(r'^login/$', login, 
        {'template_name': 'login.html', 'authentication_form': AuthenticationForm, 'redirect_authenticated_user': True}, 
        name='login'),
    url(r'^logout/$', logout, 
        {'next_page': settings.LOGIN_URL}, 
        name="logout"),
    url(r'^password_change/$', password_change,
        {'template_name': 'password_change.html', 'password_change_form': PasswordChangeForm}, 
        name='password_change'),
    url(r'^password_change/done/$', password_change_done, 
        {'template_name': 'password_change_done.html'},
        name='password_change_done'),
    url(r'^password_reset/$', password_reset,
        {'template_name': 'password_reset.html',
         'password_reset_form': PasswordResetForm},
        name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done,
        {'template_name': 'password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, 
        {'template_name': 'password_reset_confirm.html', 'set_password_form': SetPasswordForm},
        name='password_reset_confirm'),
    url(r'reset/done/$', password_reset_complete, 
        {'template_name': 'password_reset_complete.html'},
        name='password_reset_complete'),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

nutricion/urls.py
from django.conf.urls import url

from . import views

app_name = 'nutricion'
urlpatterns = [
    url(r'^$', views.index, name="indexF"),
    url(r'^ficha/$', views.crear_ficha, name="crear_ficha"),
    url(r'^ficha/lista/$', views.listar_fichas, name="listar_fichas"),
    url(r'^(?P<ficha_id>[0-9]+)/$', views.detalleFicha, name='detail'),
    url(r'(?P<ficha_id>[0-9]+)/eliminar/$', views.eliminar_ficha, name="eliminar_ficha"),
    url(r'^editar/(?P<ficha_id>[0-9]+)/$', views.editar_ficha, name='editar_ficha'),
    url(r'^reporte/(?P<cedula>[0-9]+)/$', views.reporteByCedula),
    url(r'^reporte/$', views.reporte),
    url(r'^reportes/$', views.reportes, name="reportes"),
    url(r'^horario/$', views.establecer_horario, name="crear_horario"),
    url(r'^horario/ver/$', views.ver_horarios, name="ver_horarios"),
    url(r'(?P<horario_id>[0-9]+)/cita/eliminar/$', views.eliminar_cita, name="eliminar_cita"),
]

nutricion/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from kalaapp.models import TimeModel
from personal.models import Personal
from paciente.models import Paciente
#from django.utils.timezone import  now
from django.utils import timezone
import datetime

FRECUENCIA = (
    ('diario', (
            ('vinyl', 'Vinyl'),
            ('cd', 'CD'),
        )
    ),
    ('semanal', (
            ('vhs', 'VHS Tape'),
            ('dvd', 'DVD'),
        )
    ),
    ('rara_vez', 'raraVez'),
    ('nunca', 'nunca'),
)

TIPO =(('diario', 'Diario'),
        ('semanal', 'Semanal'),
        ('raravez', 'Rara vez'),
       ('nunca', 'Nunca'))

VECES= (('1', '4-5 veces'),
        ('2', '2-3 veces'),
        ('3', '1 vez'),
        ('4', 'Rara vez'),
        ('5', 'Nunca'))

ESTADO = (('1', 'No tomada'),
          ('2', 'Finalizada'))

class ficha_nutricion(TimeModel):
    personal = models.ForeignKey(Personal, on_delete=models.DO_NOTHING)
    paciente = models.ForeignKey(Paciente, on_delete=models.DO_NOTHING)

    #Frecuencia de consumo
    lacteos = models.CharField(max_length=200, choices=TIPO, default='diario', null=False)
    vegetales = models.CharField(max_length=200, choices=TIPO, default='semanal', null=False)
    frutas = models.CharField(max_length=200, choices=TIPO, default='diario', null=False)
    cho = models.CharField(max_length=200, choices=TIPO, default='diario', null=False)
    carnes = models.CharField(max_length=200, choices=TIPO, default='diario', null=False)
    comidas_rapidas = models.CharField(max_length=200, choices=TIPO, default='diario', null=False)
    frituras = models.CharField(max_length=200, choices=TIPO, default='diario', null=False)
    enlatados = models.CharField(max_length=200, choices=TIPO, default='diario', null=False)
    gaseosas = models.CharField(max_length=200, choices=TIPO, default='diario', null=False)
    energizantes = models.CharField(max_length=200, choices=TIPO, default='diario', null=False)
    infusiones = models.CharField(max_length=200, choices=TIPO, default='diario', null=False)

    lacteos_input = models.CharField(max_length=20,choices=VECES, default='3', null=False)
    vegetales_input = models.CharField(max_length=20,choices=VECES, default='3', null=False)
    frutas_input = models.CharField(max_length=20,choices=VECES, default='3', null=False)
    cho_input = models.CharField(max_length=20,choices=VECES, default='3', null=False)
    carnes_input = models.CharField(max_length=20,choices=VECES, default='3', null=False)
    comidas_rapidas_input = models.CharField(max_length=20,choices=VECES, default='3', null=False)
    frituras_input = models.CharField(max_length=20,choices=VECES, default='3', null=False)
    enlatados_input = models.CharField(max_length=20,choices=VECES, default='3', null=False)
    gaseosas_input = models.CharField(max_length=20,choices=VECES, default='3', null=False)
    energizantes_input = models.CharField(max_length=20,choices=VECES, default='3', null=False)
    infusiones_input = models.CharField(max_length=20,choices=VECES, default='3', null=False)

    #Anamnesis alimentaria
    pregunta1= models.CharField(max_length=100, null=False)
    pregunta2 = models.CharField(max_length=100, null=False)
    pregunta3 = models.CharField(max_length=100, null=False)
    pregunta4 = models.CharField(max_length=100, null=False)
    pregunta5 = models.CharField(max_length=100, null=False)
    pregunta6 = models.CharField(max_length=100, null=False)

    #Requerimientos
    proteina = models.PositiveSmallIntegerField(null=False)
    grasas = models.PositiveSmallIntegerField(null=False)
    carbohidratos = models.PositiveSmallIntegerField(null=False)
    dieta = models.CharField(max_length=100, null=False)


    class Meta:
        #managed = False
        db_table = 'ficha_nutricion'

class HorarioNut(TimeModel):
    personal = models.ForeignKey(Personal, on_delete=models.DO_NOTHING)
    paciente = models.ForeignKey(Paciente, on_delete=models.DO_NOTHING, null=True, blank=True)

    fecha = models.DateField(auto_now=False)
    hora = models.TimeField(auto_now=False)
    duracion = models.PositiveSmallIntegerField(default=10, null=False)
    detalle = models.CharField(max_length=200, null=False)
    estado = models.CharField(max_length=200, choices=ESTADO, default='1', null=False)

    class Meta:
        db_table = 'horario_nut'

nutricion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from django.db import transaction
from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponseRedirect
from django.http import JsonResponse, HttpResponseServerError, HttpResponseNotFound
from kalaapp.decorators import rol_required
from paciente.models import Paciente, PacientePersonal
from personal.models import Personal
from .models import ficha_nutricion, HorarioNut
from .forms import FichaForm, HorariosForm

#fichasCache = []
#pacientesCache = []

def index(request):
    template = "nutricion/index.html"
    return render(request, template, { 'nutricionista': True})

@transaction.atomic
def crear_ficha(request):
    template = "nutricion/crear-ficha.html"
    form = FichaForm(request.POST or None)
    pacientes = Paciente.objects.all()
    sesion = request.session.get('user_sesion', None)
    #p = PacientePersonal.objects.filter(personal=sesion.get('personal__id', 0))
    print  sesion
    print sesion.get('personal__id', 0)
    print form._errors
    if form.is_valid():
        ficha = form.save(commit=False)
        print request.POST.get('paciente')
        paciente_id = request.POST.get('paciente')
        paciente = get_object_or_404(Paciente, pk=paciente_id)
        personal = get_object_or_404(Personal, pk=sesion.get('personal__id', 0))
        print personal
        ficha.paciente = paciente
        ficha.personal = personal
        ficha.save()
        return HttpResponseRedirect("/nutricion/ficha/lista/")
    context = {
        'form': form,
        'nutricionista': True,
        "pacientes": pacientes
    }
    return render(request, template, context)


def listar_fichas(request):
    #global fichasCache
    #global pacientesCache

    #if len(fichasCache) == 0:
    fichas = ficha_nutricion.objects.all()
    #    fichasCache = fichas
    #    print "desde la base"
    #else:
    #    fichas = fichasCache
    #    print "desde el cache"


    #if len(pacientesCache) == 0:
    pacientes = Paciente.objects.all()
    #    pacientesCache = pacientes
    #    print "desde la base"
    #else:
    #    pacientes = pacientesCache
    #    print "desde el cache"



    template = "nutricion/listar-fichas.html"
    #pacientes = Paciente.objects.all()
    #fichas = ficha_nutricion.objects.all()
    context = {
        'fichas': fichas,
        "pacientes": pacientes
    }
    return render(request, template, context)

@transaction.atomic
def eliminar_ficha(request, ficha_id):
    ficha = ficha_nutricion.objects.get(pk=ficha_id)
    ficha.delete()
    return HttpResponseRedirect("/nutricion/ficha/lista/")

@transaction.atomic
def editar_ficha(request, ficha_id):

    ficha_nutri = get_object_or_404(ficha_nutricion, pk=ficha_id)
    template = "nutricion/crear-ficha.html"
    form = FichaForm(request.POST or None, instance=ficha_nutri)
    pacientes = Paciente.objects.all()
    sesion = request.session.get('user_sesion', None)
    if form.is_valid():
        ficha = form.save(commit=False)
        paciente_id = request.POST.get('paciente')
        paciente = get_object_or_404(Paciente, pk=paciente_id)
        personal = get_object_or_404(Personal, pk=sesion.get('personal__id', 0))
        ficha.paciente = paciente
        ficha.personal = personal
        ficha.save()
        return HttpResponseRedirect("/nutricion/ficha/lista/")
    context = {
        'form': form,
        'ficha': ficha_nutri,
        'flag': True,
        "pacientes": pacientes
    }
    return render(request, template, context)

'''
Funcion: detalleFichas
Entradas: requerimiento e Identificador de la ficha a ser visualizada
Salidas:Template para renderizacion
*Funcion que recibe el id de una ficha que debe ser visualizada, y muestra su informacion.*
'''

def detalleFicha(request, ficha_id):
    contexto = {}
    ficha = None
    template = None
    paciente = None
    template = 'nutricion/ficha-detalle.html'
    ficha = get_object_or_404(ficha_nutricion, pk=ficha_id)
    form = FichaForm(request.POST or None, instance=ficha)
    contexto['form'] = form
    contexto['ficha'] = ficha
    contexto['paciente'] = ficha.paciente
    return render(request, template_name=template, context=contexto)


@transaction.atomic
def establecer_horario (request):
    template= 'nutricion/crear-horario.html'
    form = HorariosForm(request.POST or None)
    sesion = request.session.get('user_sesion', None)
    print form._errors
    if form.is_valid():
        horario = form.save(commit=False)
        personal = get_object_or_404(Personal, pk=sesion.get('personal__id', 0))
        horario.personal = personal
        horario.save()
        return HttpResponseRedirect("/nutricion/horario/ver/")
    context ={
        "form" : form
    }
    return render(request, template, context)

def ver_horarios(request):
    template = "nutricion/listar-horarios.html"
    horarios = HorarioNut.objects.all()
    context = {
        "horarios": horarios,
    }
    return render(request, template, context)

'''
Funcion: reporteTotal
Entradas: request
Salidas: JSON con los datos de todas las facturas

Funcion que permite obtener todas las facturas creadas
'''
#@login_required
def reporteByCedula(request, cedula):
    fichas = ficha_nutricion.objects.all()
    pacientes = Paciente.objects.all()

    #records = []

    for paciente in pacientes:
        if paciente.usuario.cedula == cedula:
            nombre = paciente.usuario.nombre
            apellido = paciente.usuario.apellido
            paciente_id = paciente.usuario.id

            obj = {"nombre": nombre, "apellido": apellido, "id": paciente_id, "fichas": []}

            for ficha in fichas:
                if ficha.paciente.usuario.id == paciente_id:
                    proteina = ficha.proteina
                    grasas = ficha.grasas
                    carbohidratos =  ficha.carbohidratos
                    dieta = ficha.dieta
                    record = {"proteina": proteina, "grasas": grasas, "carbohidratos": carbohidratos, "dieta": dieta}
                    obj['fichas'].append(record)
            return JsonResponse(obj)


'''
Funcion: reporteTotal
Entradas: request
Salidas: JSON con los datos de todas las facturas

Funcion que permite obtener todas las facturas creadas
'''
#@login_required

def reporte(request):
    #global fichasCache
    pacientes = []
    sesion = request.session.get('user_sesion', None)
    personal = get_object_or_404(Personal, pk=sesion.get('personal__id', 0))
    

    try:
        #if len(fichasCache) == 0:
        fichas = ficha_nutricion.objects.all()
        #    fichasCache = fichas
        #    print "desde la base"
        #else:
         #   fichas = fichasCache
         #   print "desde el cache"

        for fic in fichas:
            if fic.personal.usuario.cedula == personal.usuario.cedula:
                cedula = fic.paciente.usuario.cedula
                nombre = fic.paciente.usuario.nombre
                apellido = fic.paciente.usuario.apellido
                genero = fic.paciente.usuario.genero
                ocupacion = fic.paciente.usuario.ocupacion

                paciente = {
                    "cedula": cedula,
                    "apellido":apellido,
                    "nombre":nombre,
                    "genero":genero,
                    "ocupacion": ocupacion,
                    "fichas": []
                }

                if paciente not in pacientes:
                    pacientes.append(paciente)

        for ficha in fichas:
            if ficha.personal.usuario.cedula == personal.usuario.cedula:
                lacteos = ficha.lacteos_input + " veces, " + ficha.lacteos
                vegetales = ficha.vegetales_input + " veces, " + ficha.vegetales
                frutas = ficha.frutas_input + " veces, " + ficha.frutas
                cho = ficha.cho_input + " veces, " + ficha.cho
                carnes = ficha.carnes_input + " veces, " + ficha.carnes
                comidas_rapidas = ficha.comidas_rapidas_input + " veces, " + ficha.comidas_rapidas
                frituras = ficha.frituras_input + " veces, " + ficha.frituras
                enlatados = ficha.enlatados_input + " veces, " + ficha.enlatados
                gaseosas = ficha.gaseosas_input + " veces, " + ficha.gaseosas
                energizantes = ficha.energizantes_input + " veces, " + ficha.energizantes
                infusiones = ficha.infusiones_input + " veces, " + ficha.infusiones

                proteina = ficha.proteina
                grasas = ficha.grasas
                carbohidratos = ficha.carbohidratos
                dieta = ficha.dieta

                frecuencia_consumo = {
                    "lacteos" : lacteos,
                    "vegetales" : vegetales,
                    "frutas" : frutas,
                    "cho" : cho,
                    "carnes" : carnes,
                    "comidas_rapidas" : comidas_rapidas,
                    "frituras" : frituras,
                    "enlatados" : enlatados,
                    "gaseosas" : gaseosas,
                    "energizantes" : energizantes,
                    "infusiones" : infusiones
                }

                requerimientos = {
                    "proteina" : proteina,
                    "grasas" : grasas,
                    "carbohidratos" : carbohidratos,
                    "dieta" : dieta
                }

                for paciente in pacientes:
                    if ficha.paciente.usuario.cedula==paciente["cedula"]:
                        paciente["fichas"].append({"frecuencia_consumo":frecuencia_consumo, "requerimientos":requerimientos})
            
        return JsonResponse({"pacientes": pacientes})
    except Exception as e:
        print e
        return HttpResponseServerError("Algo salio mal")

'''
Funcion: reportes
Entradas: requerimiento get http
Salidas: Retorna un template de reportes de ficha medica
'''

nutricion/templates/nutricion/crear-ficha.html
{%  extends 'blank.html' %}
{% load staticfiles %}
{% block title %}Nutrición - Ficha Medica{% endblock %}

{% block content %}
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Ficha Medica</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            Ingrese los datos para una nueva ficha
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#ficha-pills" data-toggle="tab">Frecuencia de Consumo</a>
                                </li>
                                <li><a href="#estado-pills" data-toggle="tab">Anamnesis Alimentaria</a>
                                </li>
                                <li><a href="#req-pills" data-toggle="tab">Requerimientos</a>
                                </li>
                            </ul>

                            <form class="form-vertical" action="" method="post" enctype="multipart/form-data">
                                <!-- Tab panes -->
                                <div class="tab-content">
                                    {% include 'nutricion/ficha-template.html' %}
                                </div>

                                <div class="row" style="padding-top: 20px">
                                    <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                                        <div class="form-group">
                                            {%  if not flag %}
                                                <button type="submit" class="col-md-4 col-md-offset-4 btn btn-outline btn-success">Crear ficha</button>
                                            {%  else %}
                                                <button type="submit" class="col-md-4 col-md-offset-4 btn btn-outline btn-success">Modificar</button>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </form>

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
            </div>
    </div>
{% endblock %}

nutricion/templates/nutricion/crear-horario.html
{%  extends 'blank.html' %}
{% load staticfiles %}
{% block title %}Nutricion - Horarios{% endblock %}

{% block content %}
    {{ form.media }}
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Establecer Horario</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            Ingrese los datos para establecer su horario de cita
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <form class="form-vertical" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row" style="padding-top: 20px">
                                    <div class="col-lg-8 col-md-8 col-xs-8 col-sm-8">
                                        <div class="form-group">
                                             <label class="control-label">{{ form.fecha.label_tag }}</label>
                                             {{ form.fecha }}
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">{{ form.hora.label_tag }}</label>
                                            {{ form.hora }}
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">{{ form.duracion.label_tag }}</label>
                                            {{ form.duracion }}
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">{{ form.detalle.label_tag }}</label>
                                            {{ form.detalle }}
                                        </div>
                                        <div class="form-group ">
                                            <label class="control-label">{{ form.estado.label_tag }}</label>
                                            {{ form.estado }}
                                        </div>
                                </div>
                                <div class="row" style="padding-top: 20px">
                                    <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                                        <div class="form-group">
                                            {%  if not flag %}
                                                <button type="submit" class="col-md-4 col-md-offset-4 btn btn-outline btn-success">Crear</button>
                                            {%  else %}
                                                <button type="submit" class="col-md-4 col-md-offset-4 btn btn-outline btn-success">Modificar</button>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </form>

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
            </div>
    </div>
{% endblock %}


{% block script %}

{% endblock %}

nutricion/templates/nutricion/index.html
{% extends 'blank.html'%}
{% block content %}

{% endblock %}

nutricion/templates/nutricion/listar-fichas.html
{%  extends 'blank.html' %}
{% load staticfiles %}
{% block title %}Fisioterapia - Ficha Medica{% endblock %}

{% block content %}
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Fichas Medicas</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                           Lista de fichas medicas de los pacientes
                        </div>
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>Detalle</th>
                                        <th>Foto</th>
                                        <th>Nombre </th>
                                        <th>Apellido</th>
                                        <th>Fecha</th>
                                        <th>% Proteinas</th>
                                        <th>% Grasas</th>
                                        <th>% Carbohidratos</th>
                                        <th>Editar</th>
                                        <th>Eliminar</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if fichas %}
                                        {% for ficha in fichas %}
                                            <tr class="">
                                                <td style="text-align: center;"><a href="{% url 'nutricion:detail' ficha.id %}"><button type="submit" class="btn btn-default">
                                                    <span class="glyphicon glyphicon-eye-open"></span>
                                                    </button></a></td>
                                                <td><img src="/static/{{ ficha.paciente.usuario.foto }}" class="img-responsive" height="50px" width="50px"/></td>
                                                <td class="capitalize">{{ ficha.paciente.usuario.nombre }}</td>
                                                <td class="capitalize">{{ ficha.paciente.usuario.apellido }}</td>
                                                <td>{{ ficha.actualizado }}</td>
                                                <td>{{ ficha.proteina }}</td>
                                                <td>{{ ficha.grasas }}</td>
                                                <td>{{ ficha.carbohidratos }}</td>
                                                <td style="text-align: center;"><a href="{% url 'nutricion:editar_ficha' ficha.id %}">
                                                    <button type="submit" class="btn btn-info">
                                                        <p class="fa fa-edit "></p>
                                                    </button>
                                                </a></td>
                                                <td style="text-align: center;"><a href="{%  url 'nutricion:eliminar_ficha' ficha.id %}">
                                                    <button type="submit" class="btn btn-danger">
                                                        <span class="glyphicon glyphicon-remove"></span>
                                                    </button>
                                                   </a></td>
                                            </tr>
                                        {% endfor %}
                                    {% endif %}
                                </tbody>
                            </table>
                            <!-- /.table-responsive -->
                        </div>
                    </div>
                    <!-- /.panel -->
                </div>
            </div>
    </div>

{% endblock %}

nutricion/templates/nutricion/listar-horarios.html
{%  extends 'blank.html' %}
{% load staticfiles %}
{% block title %}Nutricion - Horarios{% endblock %}

{% block content %}
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Ver Horarios</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                           Horarios disponibles
                        </div>
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>Fecha</th>
                                        <th>Hora</th>
                                        <th>Detalle</th>
                                        <th>Estado</th>
                                        <th>Paciente</th>
                                        <th>Duracion</th>
                                        <th>Cancelar</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if horarios %}
                                        {% for horario in horarios %}
                                            <tr class="">
                                                <td>{{ horario.fecha }}</td>
                                                <td>{{ horario.hora }}</td>
                                                <td>{{ horario.detalle }}</td>
                                                <td>{{ horario.get_estado_display }}</td>
                                                <td> {% if horario.paciente %}
                                                    {{ horario.paciente }}
                                                {% else %}
                                                    No asignado
                                                {% endif %}</td>
                                                 <td>{{ horario.duracion }} - Minutos</td>
                                                <td><a href="{% url 'nutricion:eliminar_cita' horario.id %}">
                                                    <button type="submit" class="btn btn-danger">
                                                        <span class="glyphicon glyphicon-remove"></span>
                                                    </button>
                                                   </a></td>
                                            </tr>
                                        {% endfor %}
                                    {% endif %}
                                </tbody>
                            </table>
                            <!-- /.table-responsive -->
                        </div>
                    </div>
                    <!-- /.panel -->
                </div>
            </div>
    </div>

{% endblock %}